# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
    lane :sit do
      ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= 'your-password'
      build_app(workspace: "Runner.xcworkspace", scheme: "sit")
      upload_to_testflight(
        changelog: "New app version",
        username:"your-apple-email",
        team_name:"your-team-name",
        skip_submission:true,
        skip_waiting_for_build_processing:true)
    end

    lane :prod do
      ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= 'your-password'
      build_app(workspace: "Runner.xcworkspace", scheme: "prod")
      upload_to_testflight(
        changelog: "New app version",
        username:"your-apple-email",
        team_name:"your-team-name",
        skip_submission:true,
        skip_waiting_for_build_processing:true)
    end
end
