# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    lane :sit do
        firebase_app_distribution(
             app: "your-app-id",
             firebase_cli_path: "/usr/local/bin/firebase",
             groups:"test",
             apk_path: "..//build/app/outputs/flutter-apk/app-sit-release.apk",
             release_notes: "New demo")
    end

    lane :prod do
        firebase_app_distribution(
             app: "your-app-id",
             firebase_cli_path: "/usr/local/bin/firebase",
             groups:"test",
             apk_path: "..//build/app/outputs/flutter-apk/app-prod-release.apk",
             release_notes: "New demo")
    end

end